server:
  port: 9090
---
spring:
  # DB DataSource 설정
  datasource:
    # MYSQL
    #url: jdbc:mysql://127.0.0.1:3306/springBootDemo
    #username: root
    #password: kmy5708!@#

    # h2
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

  # view Template Engine 설정 > Thymeleaf
  thymeleaf:
    #mode: HTML
    #encoding: UTF-8
    #check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false   #(개발모드 : false, 운영모드 : true)

  # static resource에 변화가 있을 때 바로반영(build Automaticall 해야됨)
  devtools:
    livereload:
      enabled: true

  # h2(in Memory RDBMS) 관련
  h2:
    console:
      enabled: true

  # JPA 관련
  jpa:
    show-sql: true  # JPA가 생성하는 SQL을 출력
    hibernate:
      ddl-auto: none # JPA는 테이블을 자동으로 생성하는 기능을 제공하는데 none를 사용하면 해당 기능을 끔, create : 엔티티정보를 바탕으로 테이블 직접 생성